{{- if .Values.service.port -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helxapp_controller.fullname" . }}
  labels:
    {{- include "helxapp_controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helxapp_controller.selectorLabels" . | nindent 4 }}
{{- end }}
