# permissions for end users to edit helxappinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: helxappinstance-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: builder
    app.kubernetes.io/part-of: builder
    app.kubernetes.io/managed-by: kustomize
  name: helxappinstance-editor-role
  namespace: jeffw
rules:
- apiGroups:
  - helx.renci.org
  resources:
  - helxappinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helx.renci.org
  resources:
  - helxappinstances/status
  verbs:
  - get
