# permissions for end users to edit helxapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: helxapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: builder
    app.kubernetes.io/part-of: builder
    app.kubernetes.io/managed-by: kustomize
  name: helxapp-editor-role
  namespace: jeffw
rules:
- apiGroups:
  - helx.renci.org
  resources:
  - helxapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helx.renci.org
  resources:
  - helxapps/status
  verbs:
  - get
