---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: helxapp-manager
  namespace: jeffw
rules:
  - apiGroups:
      - "renci.org"
    resources:
      - "helxapps"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helxapp-manager-binding
  namespace: jeffw
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: helxapp-manager
subjects:
  - kind: ServiceAccount
    name: jeffw
    namespace: jeffw
