apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helxapps.renci.org
spec:
  group: renci.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                services:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      image:
                        type: string
                      ports:
                        type: array
                        items:
                          type: object
                          properties:
                            containerPort:
                              type: integer
                            hostPort:
                              type: integer
                      environment:
                        type: object
                        additionalProperties:
                          type: string
                      volumes:
                        type: array
                        items:
                          type: object
                          properties:
                            mountPath:
                              type: string
                            hostPath:
                              type: string
                      replicas:
                        type: integer
  scope: Namespaced
  names:
    plural: helxapps
    singular: helxapp
    kind: HeLxApp
    shortNames:
      - ha
